#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
NC='\033[0m'

FLAKE="macos"
SYSTEM="darwinConfigurations.$FLAKE.system"
# Github repo to build from
GITHUB="github:tunamelon/nix-config"

export NIXPKGS_ALLOW_UNFREE=1

echo "${GREEN}Starting build...${NC}"
nix --experimental-features 'nix-command flakes' build $GITHUB#$SYSTEM $@

echo "${GREEN}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
