#!/bin/bash -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
  x86_64)
    FLAKE_TARGET="x86_64-linux"
    ;;
  aarch64)
    FLAKE_TARGET="aarch64-linux"
    ;;
  *)
    echo -e "${RED}Unsupported architecture: $SYSTEM${NC}"
    exit 1
    ;;
esac

echo -e "${YELLOW}Starting...${NC}"

# Determine if the system is NixOS or not
if [ -e /etc/NIXOS ]; then
    # NixOS specific command
    echo "Running on NixOS"
    sudo SSH_AUTH_SOCK=$SSH_AUTH_SOCK /run/current-system/sw/bin/nixos-rebuild switch --flake .#$FLAKE_TARGET $@
else
    # Assuming it's Debian with Nix and home-manager installed
    echo "Running on non-NixOS, possibly Debian"
    # Home-manager command (adjust as needed)
    SSH_AUTH_SOCK=$SSH_AUTH_SOCK /home/tuna/nix-config/home-manager switch --flake .#$FLAKE_TARGET $@
fi

echo -e "${GREEN}Switch to new generation complete!${NC}"
